owner: grasshopperfund # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Grasshopperfund
    url: https://www.grasshopperfund.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.grasshopperfund.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/grasshopperfund/status/0f585e66481b8b5b868f474ffb1440f4a374fca4/assets/logo.svg
  name: Grasshopperfund Status
  introTitle: "See the current status of Grasshopperfund, as well as any past/ongoing incidents"
  introMessage: Have any concerns? Check out https://form.typeform.com/to/kL6w15tG
  navbar:
    - title: Status
      href: /
    - title: Grasshopperfund
      href: https://grasshopperfund.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
